# Generated by Django 5.0.3 on 2024-05-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100, null=True)),
                ('std_id', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('Joining_date', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=100, null=True)),
                ('img', models.CharField(max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('father_occu', models.CharField(max_length=100, null=True)),
                ('father_phone', models.CharField(max_length=100, null=True)),
                ('father_email', models.CharField(max_length=100, null=True)),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('mother_occu', models.CharField(max_length=100, null=True)),
                ('mother_phone', models.CharField(max_length=100, null=True)),
                ('mother_email', models.CharField(max_length=100, null=True)),
                ('department_add', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_season', models.CharField(max_length=50, null=True)),
                ('end_season', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
