# Generated by Django 5.0.3 on 2024-05-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_add_student_permanent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_teacher_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100, null=True)),
                ('teacher_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('Joining_date', models.CharField(max_length=100, null=True)),
                ('edu_qualofy', models.CharField(max_length=100, null=True)),
                ('experience', models.PositiveIntegerField(max_length=100, null=True)),
                ('t_username', models.CharField(max_length=100, null=True)),
                ('t_email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('present_address', models.CharField(max_length=100, null=True)),
                ('permanent_address', models.CharField(max_length=100, null=True)),
                ('t_img', models.ImageField(null=True, upload_to='static/media/teacher_pic')),
            ],
        ),
        migrations.AlterField(
            model_name='add_student',
            name='img',
            field=models.ImageField(null=True, upload_to='static/media/student_pic'),
        ),
    ]
