# Generated by Django 5.0.6 on 2024-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0006_add_student_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='department_model',
        ),
        migrations.AlterField(
            model_name='add_teacher_model',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
