# Generated by Django 5.0.6 on 2024-05-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0008_rename_edu_qualofy_add_teacher_model_edu_qualify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_student',
            name='department_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='std_department', to='SchoolApp.department_model'),
        ),
    ]
