# Generated by Django 5.0.3 on 2024-05-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0008_rename_edu_qualofy_add_teacher_model_edu_qualify_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.IntegerField(max_length=20, null=True)),
                ('subject_name', models.CharField(max_length=20, null=True)),
                ('subject_add_dep', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
