# Generated by Django 5.0.3 on 2024-06-09 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={'ordering': ['last_name'], 'verbose_name': 'Coustom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='custom_user',
            unique_together={('username', 'email')},
        ),
        migrations.AlterModelTable(
            name='custom_user',
            table='my_to_do_list_table',
        ),
        migrations.CreateModel(
            name='categoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=100, null=True)),
                ('Data', models.DateField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_list.categorymodel')),
            ],
            options={
                'unique_together': {('category', 'TaskName')},
            },
        ),
    ]
