# Generated by Django 5.0.3 on 2024-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_custom_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Data',
            new_name='complite_Data',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='create_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='due_Data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(default='On_Going', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='taskmodel',
            table='My Task Model',
        ),
    ]
