# Generated by Django 5.0.3 on 2024-05-02 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_alter_jobrecruiter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecruiter_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobrecruiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
