# Generated by Django 5.0.3 on 2024-05-05 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_alter_jobrecruiter_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, null=True)),
                ('institute', models.CharField(max_length=100, null=True)),
                ('gpa', models.CharField(max_length=100, null=True)),
                ('passingyear', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
