# Generated by Django 5.0.3 on 2024-05-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0004_educationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='highest_edu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
