# Generated by Django 5.0.3 on 2024-06-05 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0005_jobseeker_profile_highest_edu'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='static/media/applycant_pic')),
                ('resume', models.FileField(null=True, upload_to='static/media/applycant_resume')),
                ('qualification', models.CharField(max_length=500, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobApp.add_job')),
            ],
        ),
    ]
