# Generated by Django 5.0.3 on 2024-06-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0006_apply_job_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job_model',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
