# Generated by Django 5.0.3 on 2024-06-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0007_apply_job_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job_model',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
