# Generated by Django 5.0.4 on 2024-04-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='digree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dig_name', models.CharField(max_length=30, null=True)),
                ('dig_lavel', models.CharField(max_length=30, null=True)),
                ('dig_point', models.CharField(max_length=50, null=True)),
                ('dig_year', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('company_summary', models.TextField(null=True)),
                ('company_address', models.CharField(max_length=50, null=True)),
                ('company_role', models.CharField(max_length=20, null=True)),
                ('company_joining', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='hsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=30, null=True)),
                ('h_lavel', models.CharField(max_length=30, null=True)),
                ('h_point', models.CharField(max_length=50, null=True)),
                ('h_year', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('summary', models.TextField(null=True)),
                ('skills', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(null=True, upload_to='media/image')),
            ],
        ),
        migrations.CreateModel(
            name='ssc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30, null=True)),
                ('s_lavel', models.CharField(max_length=30, null=True)),
                ('s_point', models.CharField(max_length=50, null=True)),
                ('s_year', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
