# Generated by Django 5.0.4 on 2024-04-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_personal_info_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
