# Generated by Django 5.0.4 on 2024-04-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_personal_info_email_personal_info_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
