# Generated by Django 5.0.4 on 2024-04-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_personal_info_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
