# Generated by Django 5.0.4 on 2024-04-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_personal_info_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='skills',
            new_name='website',
        ),
    ]
