# Generated by Django 5.0.4 on 2024-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='s_js',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='s_php',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='s_python',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='s_sql',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
