# Generated by Django 5.0.4 on 2024-04-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_alter_skill_s_js_alter_skill_s_php_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digree',
            name='dig_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsc',
            name='h_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ssc',
            name='s_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
