# Generated by Django 5.0.4 on 2024-04-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_alter_digree_dig_lavel_alter_hsc_h_lavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digree',
            name='dig_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hsc',
            name='h_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ssc',
            name='s_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
