# Generated by Django 5.0.3 on 2024-04-20 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0011_digree_dig_address_hsc_h_address_ssc_s_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='digree',
        ),
        migrations.DeleteModel(
            name='hsc',
        ),
    ]
