# Generated by Django 5.0.3 on 2024-04-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0012_delete_digree_delete_hsc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ssc',
            new_name='education',
        ),
    ]
