# Generated by Django 5.0.3 on 2024-04-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApp', '0002_student_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='std_img',
            field=models.ImageField(null=True, upload_to='media/student'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='roll',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
