# Generated by Django 5.0.3 on 2024-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApp', '0003_student_model_std_img_alter_student_model_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_model',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='candidate_model',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='candidate_model',
            name='language',
        ),
        migrations.RemoveField(
            model_name='candidate_model',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='candidate_model',
            name='university',
        ),
        migrations.RemoveField(
            model_name='candidate_model',
            name='yoe',
        ),
        migrations.AddField(
            model_name='candidate_model',
            name='img',
            field=models.ImageField(null=True, upload_to='media/candidate'),
        ),
    ]
