# Generated by Django 5.0.4 on 2024-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0005_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
