# Generated by Django 5.0.4 on 2024-06-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0006_jobapplymodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplymodel',
            name='status',
        ),
    ]
