# Generated by Django 5.0.6 on 2024-06-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_options_categorymodel_taskmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name'], 'verbose_name': 'Custom User'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='to_do_list_table',
        ),
    ]
