# Generated by Django 5.0.6 on 2024-06-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='my_to_do_list_table',
        ),
    ]
