# Generated by Django 5.0.6 on 2024-06-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('username', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='taskmodel',
            unique_together={('category', 'TaskName')},
        ),
    ]
