# Generated by Django 5.0.6 on 2024-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Date',
            new_name='completed_date',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(default='On_Going', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
