# Generated by Django 5.0.6 on 2024-05-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('dep', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
    ]
